" in WIndows, create: %userprofile%\vimfiles\vimrc
" Which is C:\Users\mrcooper\vimfiles
" Then restart cygwin
"  cp vimrc /cygdrive/c/Users/mrcooper/vimfiles/
filetype plugin on
filetype indent on

syntax on
set path+=./**
set makeprg=build
set smartcase
set ff=unix

" highlight spurious whitespace before the linter does
highlight ExtraWhitespace ctermbg=lightgreen guibg=lightgreen
match ExtraWhitespace /\s\+$/

" backups are a little silly when you're using patches constantly
set nobackup
set noswapfile
